name: 构建程序
on: 
  push:
    branches:
      - '**'
  pull_request:
  
jobs:
  Build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        runtimeIdentifier: [ win-x64, linux-x64]

    name: 构建插件
    steps:
      - uses: actions/checkout@v4
        with:
           submodules: 'recursive'
           
      - name: 初始化.NET 8
        uses: actions/setup-dotnet@v4
        env:
          DOTNET_CLI_UI_LANGUAGE: zh-CN
        with:
          dotnet-version: 9.0.x
          
      - name: 构建插件
        run: |
          dotnet publish Lagrange.XocMat/Lagrange.XocMat.csproj --no-self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }} --framework net9.0
          
      - name: 安装 zip
        run: sudo apt-get install zip

      - name: 生成压缩包
        run: zip -r -j Lagrange.XocMat_${{ matrix.runtimeIdentifier }}_9.0.zip Lagrange.XocMat/bin/Release/net9.0/${{ matrix.runtimeIdentifier }}/publish/
      
      - name: 上传临时文件
        uses: actions/-artifuploadact@v4
        with:
          name: Lagrange.XocMat_${{ matrix.runtimeIdentifier }}_9.0
          path: Lagrange.XocMat_${{ matrix.runtimeIdentifier }}_9.0.zip
          
  LatestRelease:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: 发布
    runs-on: ubuntu-24.04
    needs: Build
    permissions:
         contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 更新发布标签
        run: |
          git tag -f V1.0.0.0
          git push -f origin V1.0.0.0
      - name: 下载临时插文件
        uses: actions/download-artifact@v4
        with:
            path: bin
            merge-multiple: true
      - name: 拆分压缩包
        run: ls -R bin
      - name: 发布Release
        uses: ncipollo/release-action@v1
        with:
          tag: V1.0.0.0
          name: "最新版本"
          body: ""
          artifacts: |
            ./bin/*
          allowUpdates: true
          removeArtifacts: true
              
         
  ClearTempArtifacts:
    name: 清理临时文件
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && always()
    runs-on: ubuntu-24.04
    needs:
      - LatestRelease
    permissions:
      actions: write
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            Artifacts
