name: Lagrange.XocMat NuGet Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    name: 发布Lagrange.XocMat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
           submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: dotnet build --configuration Release --no-restore

      - name: Add private GitHub registry to NuGet MorMor
        run: dotnet nuget add source --username Controllerdestiny --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Lagrange.XocMat/index.json"
        
      - name: Pack A project
        run: dotnet pack --configuration Release --output ./nupkg ./Lagrange.XocMat/Lagrange.XocMat.csproj  # 确保路径正确

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }}
