name: Lagrange.XocMat NuGet Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    name: 发布Lagrange.XocMat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Pack
        run: |
            dotnet build -c Release Lagrange.XocMat/Lagrange.XocMat.csproj
            dotnet pack -c Release Lagrange.XocMat/Lagrange.XocMat.csproj
            dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg Lagrange.XocMat/Lagrange.XocMat.csproj
            
      - name: Add private GitHub registry to NuGet Lagrange.XocMat
        run: dotnet nuget add source --username Controllerdestiny --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Lagrange.XocMat/index.json"

      - name: Push generated package to NuGet Lagrange.XocMat
        run: dotnet nuget push ./Lagrange.XocMat/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }}
